# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# C:\b\abs_0cunwx_ww6\clone\recipe, last modified Thu Oct  3 19:29:26 2024
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.6
source:
  sha256: 8b27e6a217e786c6fbe5634d8f3f11bc63e0f80f6a5890f28863d9c45aac311b
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.6.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_0cunwx_ww6\\croot\\ruamel.yaml_1727980181547\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py312h827c3e9_0
requirements:
  build:
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.6 h14ffc60_1
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024a h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
    - ruamel.yaml.clib >=0.2.7
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - pip check
  imports:
    - ruamel.yaml
  requires:
    - pip
about:
  description: A YAML parser/emitter that supports roundtrip preservation of comments,
    seq/map flow style, and map key order
  dev_url: https://sourceforge.net/projects/ruamel-yaml/
  doc_url: https://yaml.readthedocs.io
  home: https://sourceforge.net/projects/ruamel-yaml/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0c893957-2229-4d86-a52b-150c53470577
  recipe-maintainers:
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/ruamel.yaml-feedstock.git
  sha: 8012248d4e2e83b9364b0bfca47dc9de18884ecb
