# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# C:\b\abs_12ybmrg1d4\clone\recipe, last modified Wed Jan 29 16:32:50 2025
# ------------------------------------------------

package:
  name: conda
  version: 25.1.1
source:
  sha256: 12aeb248b3c1c598f3512425571de3a5aa8737fd8f1001a5ea32156ac4745f53
  url: https://github.com/conda/conda/releases/download/25.1.1/conda-25.1.1.tar.gz
build:
  always_include_files:
    - Scripts/activate
    - Scripts/activate.bat
    - Scripts/deactivate
  number: '0'
  script: C:\\b\\abs_12ybmrg1d4\\croot\\conda_1738168389704\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv && C:\\b\\abs_12ybmrg1d4\\croot\\conda_1738168389704\\_h_env\\python.exe
    -m conda init --install
  string: py312haa95532_0
requirements:
  build:
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
  host:
    - boltons 24.1.0 py312haa95532_0
    - brotli-python 1.0.9 py312h5da7b33_9
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.12.31 haa95532_0
    - certifi 2024.12.14 py312haa95532_0
    - charset-normalizer 3.3.2 pyhd3eb1b0_0
    - colorama 0.4.6 py312haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - hatch-vcs 0.3.0 py312haa95532_1
    - hatchling 1.27.0 py312haa95532_0
    - idna 3.7 py312haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - menuinst 2.2.0 py312h5da7b33_0
    - openssl 3.0.15 h827c3e9_0
    - packaging 24.2 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 25.0 py312haa95532_0
    - platformdirs 3.10.0 py312haa95532_0
    - pluggy 1.5.0 py312haa95532_0
    - pysocks 1.7.1 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - requests 2.32.3 py312haa95532_1
    - ruamel.yaml 0.18.6 py312h827c3e9_0
    - ruamel.yaml.clib 0.2.8 py312h827c3e9_0
    - setuptools 75.8.0 py312haa95532_0
    - setuptools-scm 8.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tqdm 4.66.5 py312hfc267ef_0
    - trove-classifiers 2024.10.14 py312haa95532_0
    - tzdata 2025a h04d1e81_0
    - urllib3 2.3.0 py312haa95532_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.45.1 py312haa95532_0
    - win_inet_pton 1.1.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=24.11.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=3.27
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  downstreams:
    - conda-smithy
  imports:
    - conda
    - conda_env
  requires:
    - m2-base
    - m2-bash
    - m2-filesystem
about:
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://docs.conda.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 120f97a1-0b7c-473d-bd36-6765478f95a1
  remote_url: git@github.com:AnacondaRecipes/conda-feedstock.git
  sha: f6741cbf35d8cb4bc27b70fc80f2842c02d94d1f
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
