# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\mdurl-feedstock\recipe, last modified Wed Nov  8 19:27:09 2023
# ------------------------------------------------

package:
  name: mdurl
  version: 0.1.0
source:
  sha256: 94873a969008ee48880fb21bad7de0349fef529f3be178969af5817239e9b990
  url: https://pypi.io/packages/source/m/mdurl/mdurl-0.1.0.tar.gz
build:
  number: '0'
  script: C:\Users\dev-admin\perseverance-python-buildout\croot\mdurl_1699473506455\_h_env\python.exe
    -m pip install . -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - expat 2.5.0 hd77b12b_0
    - flit-core 3.9.0 py312h7146dc4_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3 py312haa95532_0
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  imports:
    - mdurl
about:
  home: https://github.com/executablebooks/mdurl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: URL utilities for markdown-it-py parser.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chrisjsewell
