# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# C:\b\abs_b1gsooouql\clone\recipe, last modified Tue Sep 24 17:58:32 2024
# ------------------------------------------------

package:
  name: anaconda_powershell_prompt
  version: 1.1.0
build:
  number: '0'
  string: haa95532_0
requirements:
  build: []
  run: []
  run_constrained:
    - anaconda-navigator >=1.9.8
    - menuinst >=2.1.1
test:
  commands:
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_powershell_prompt_menu.json EXIT 1
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_powershell_prompt.ico EXIT 1
app:
  entry: start powershell.exe -ExecutionPolicy ByPass -NoExit -Command  "& '${CONDA_ROOT_PREFIX}\\shell\\condabin\\conda-hook.ps1'
    ; conda activate '${CONDA_PREFIX}'"
  icon: anaconda_powershell_prompt.png
  summary: Opens a PowerShell instance with conda activated (requires menuinst 2.1.1
    or greater).
  type: desk
about:
  description: 'Package to create shortcuts for PowerShell with an activated conda
    environment.

    '
  dev_url: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock
  doc_url: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock/blob/main/README.md
  home: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock
  license: BSD-3-Clause AND CC-BY-NC-ND-4.0
  license_family: Other
  license_file:
    - LICENSE
    - LICENSE-BSD-3-Clause
    - LICENSE-CC-BY-NC-ND-4.0
  summary: PowerShell shortcut creator for Anaconda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b11a3026-dd0e-45ba-8d72-f5b04c20e470
  recipe-maintainers:
    - marcoesters
  remote_url: git@github.com:AnacondaRecipes/anaconda_powershell_prompt-feedstock.git
  sha: 4f92de19d9898440643c0af31c573aa5cf70ef0c
