# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_bdosz7qwys\clone\recipe, last modified Fri Dec 20 20:20:56 2024
# ------------------------------------------------

package:
  name: pydantic-core
  version: 2.27.1
source:
  sha256: 62a763352879b84aa31058fc931884055fd75089cccbd9d58bb6afd01141b235
  url: https://pypi.io/packages/source/p/pydantic-core/pydantic_core-2.27.1.tar.gz
build:
  number: '0'
  script:
    - C:\\b\\abs_bdosz7qwys\\croot\\pydantic-core_1734726071532\\_h_env\\python.exe
      -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  script_env: null
  string: py312h636fa0f_0
requirements:
  build:
    - cargo-bundle-licenses 0.5.0 h1718810_0
    - m2w64-gcc-libgfortran 5.3.0 6
    - m2w64-gcc-libs 5.3.0 7
    - m2w64-gcc-libs-core 5.3.0 7
    - m2w64-gmp 6.1.0 2
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - msys2-conda-epoch 20160418 1
    - rust 1.82.0 h5da7b33_0
    - rust_win-64 1.82.0 h5da7b33_0
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - maturin 1.5.1 py312h827c3e9_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - typing-extensions 4.12.2 py312haa95532_0
    - typing_extensions 4.12.2 py312haa95532_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
    - typing-extensions >=4.6.0,!=4.7.0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - pip check
    - python -c "from pydantic_core import PydanticUndefinedType"
  imports:
    - pydantic_core
  requires:
    - pip
about:
  description: 'This package provides the core functionality for pydantic validation
    and serialization.

    '
  dev_url: https://github.com/pydantic/pydantic-core
  doc_url: https://docs.pydantic.dev
  home: https://github.com/pydantic/pydantic-core
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Core validation logic for pydantic written in rust
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd4ba5a7-d18c-448a-a99f-225eb0b69dc0
  recipe-maintainers:
    - adriangb
    - dmontagu
    - pavelzw
    - samuelcolvin
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/pydantic-core-feedstock.git
  sha: f5cb5ac27c36d23764c5596c2208d6b1a174bec3
