# This file created by conda-build 24.11.2
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.30
source:
  patches:
    - patches/conda_variant_priorization.patch
    - patches/no_error_subdir_mismatch.patch
    - patches/pcre2-compat.patch
    - patches/win_export_and_static_build.patch
  sha256: ce4aa2f0e3c5c9ab99dced6a1810af3f670f1b98892394edc68ccabe7b272133
  url: https://github.com/openSUSE/libsolv/archive/0.7.30.tar.gz
build:
  ignore_run_exports:
    - zlib
  noarch: false
  noarch_python: false
  number: '1'
  script: install_dynamic.bat
  string: hf2fb9eb_1
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja 1.12.1 haa95532_0
    - ninja-base 1.12.1 h4157e71_0
    - openssl 3.0.15 h827c3e9_0
    - python 3.13.1 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - glib 2.78.4 hd77b12b_0
    - glib-tools 2.78.4 hd77b12b_0
    - libffi 3.4.4 hd77b12b_1
    - libglib 2.78.4 ha17d25a_0
    - libiconv 1.16 h2bbff1b_3
    - libmpdec 4.0.0 h827c3e9_0
    - openssl 3.0.15 h827c3e9_0
    - pcre2 10.42 h0ff8eda_1
    - pkg-config 0.29.2 h8cc25b3_0
    - python 3.13.1 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - pcre2 >=10.42,<10.43.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\solv\repo.h (exit 1)
    - if not exist %LIBRARY_BIN%\solv.dll (exit 1)
    - if not exist %LIBRARY_LIB%\solv.lib (exit 1)
    - if not exist %LIBRARY_BIN%\solvext.dll (exit 1)
    - if not exist %LIBRARY_LIB%\solvext.lib (exit 1)
    - if exist %LIBRARY_LIB%\solv_static.lib (exit 1)
    - if exist %LIBRARY_LIB%\solvext_static.lib (exit 1)
    - dumpsolv.exe -h
about:
  description: 'libsolv, a free package dependency solver using a satisfiability algorithm.

    '
  dev_url: https://github.com/openSUSE/libsolv
  doc_url: https://github.com/openSUSE/libsolv/tree/master/doc
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 03afa3e0-0939-414f-8207-66b21eb62016
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/libsolv-feedstock.git
  sha: 20f7f0a13a1a12d7b1ef839d650dd156df024468
