# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# C:\b\abs_7fz3aferfv\clone\recipe, last modified Mon Nov 11 23:50:25 2024
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.4.0
source:
  sha256: a68d23d795704f1b687559b89c98e73d0dbebcab077592c60bffc1dc408b72e9
  url: https://github.com/conda/conda-package-handling/archive/2.4.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  number: '0'
  script: C:\\b\\abs_7fz3aferfv\\croot\\conda-package-handling_1731369038903\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - python 3.12.7 h14ffc60_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.7 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - conda-package-streaming >=0.9.0
    - python >=3.12,<3.13.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - bottle
    - mock
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  description: '`conda` and `conda-build` use `conda_package_handling.api` to create
    and extract

    conda packages. This package also provides the `cph` command line tool to

    extract, create, and convert between formats.

    '
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Create and extract conda packages of various formats.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 7f9e9676-8d33-4c1b-9c3f-ab47e889a2ac
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
  remote_url: git@github.com:AnacondaRecipes/conda-package-handling-feedstock.git
  sha: 5851a404edf8489129ea177a94f887521160f3b0
