#!/bin/sh
_CONDA_ROOT="C:\b\abs_12ybmrg1d4\croot\conda_1738168389704\_h_env"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
