# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_18nblzzn70\clone\recipe, last modified Tue Jan 14 15:27:01 2025
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  patches:
    - patches/0001-GH-100-Replace-unittest.makeSuite-with-unittest.defaultTest.patch
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '2'
  script: C:\\b\\abs_18nblzzn70\\croot\\pycosat_1736868434419\\_h_env\\python.exe
    -m pip install . --no-deps -vv --no-build-isolation
  string: py312h827c3e9_2
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.12.31 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_url: https://github.com/conda/pycosat/blob/master/README.rst
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_url: https://github.com/conda/pycosat/blob/0.6.6/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 183090a0-4375-44a6-a8ec-15ca6b31ff85
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pycosat-feedstock.git
  sha: 3b293122c88ae0e420700408e363b20fb0b58a35
