# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_c03454m2yz\clone\recipe, last modified Thu Dec 12 21:35:05 2024
# ------------------------------------------------

package:
  name: cpp-expected
  version: 1.1.0
source:
  - sha256: 1db357f46dd2b24447156aaf970c4c40a793ef12a8a9c2ad9e096d9801368df6
    url: https://github.com/TartanLlama/expected/archive/refs/tags/v1.1.0.tar.gz
build:
  number: '0'
  string: h214f63a_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja 1.12.1 haa95532_0
    - ninja-base 1.12.1 h4157e71_0
    - openssl 3.0.15 h827c3e9_0
    - python 3.13.1 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
  run:
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\tl\expected.hpp (exit 1)
    - if not exist %LIBRARY_PREFIX%\share\cmake\tl-expected\tl-expected-config.cmake
      (exit 1)
    - if not exist %LIBRARY_PREFIX%\share\cmake\tl-expected\tl-expected-config-version.cmake
      (exit 1)
about:
  description: C++11/14/17 std::expected with functional-style extensions
  dev_url: https://github.com/TartanLlama/expected
  doc_url: https://github.com/TartanLlama/expected#readme
  home: https://github.com/TartanLlama/expected
  license: CC0-1.0
  license_family: CC
  license_file: COPYING
  summary: C++11/14/17 std::expected with functional-style extensions
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: c0259c36-ffba-4d48-967b-9e42f512c98c
  recipe-maintainers:
    - JohanMabille
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/cpp-expected-feedstock.git
  sha: 4457a27f5d09d4666580e8050590e37591484e2c
