# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# C:\b\abs_0eh9b6xugj\clone\recipe, last modified Fri Feb  7 16:25:41 2025
# ------------------------------------------------

package:
  name: tqdm
  version: 4.67.1
source:
  sha256: f8aef9c52c08c13a65f30ea34f4e5aac3fd1a34959879d7e59e63027286627f2
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.67.1.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '0'
  script: C:\\b\\abs_0eh9b6xugj\\croot\\tqdm_1738945553987\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py312hfc267ef_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.12.31 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - packaging 24.2 py312haa95532_0
    - pip 25.0 py312haa95532_0
    - python 3.12.9 h14ffc60_0
    - setuptools 75.8.0 py312haa95532_0
    - setuptools-scm 8.1.0 py312haa95532_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025a h04d1e81_0
    - vc 14.42 haa95532_3
    - vs2015_runtime 14.42.34433 he0abc0d_3
    - wheel 0.45.1 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - colorama
    - python >=3.12,<3.13.0a0
  run_constrained:
    - ipywidgets >=6
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.67.1
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - dask-core
    - numpy
    - pandas
    - pip
    - pytest >=6
    - pytest-asyncio >=0.24
    - pytest-timeout
    - pytest-xdist
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - tests
about:
  description: A Fast, Extensible Progress Bar for Python and CLI
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0eaad2aa-f10e-422b-9761-48ec2d21def4
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/tqdm-feedstock.git
  sha: 94cf0819d934b0cb8c4149ff64bbbbaad80b9ea0
