# This file created by conda-build 24.11.2
# ------------------------------------------------

package:
  name: typing-extensions
  version: 4.12.2
source:
  sha256: 1a7ead55c7e559dd4dee8856e3a88b41225abfe1ce8df57b7c13915fe121ffb8
  url: https://pypi.io/packages/source/t/typing_extensions/typing_extensions-4.12.2.tar.gz
build:
  number: 0
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - python 3.12.8 h14ffc60_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
    - typing_extensions 4.12.2 py312haa95532_0
test:
  commands:
    - pip check
  imports:
    - typing_extensions
  requires:
    - pip
about:
  description: 'The typing module was added to the standard library in Python 3.5,
    but

    many new features have been added to the module since then.

    This means users of older Python versions who are unable to upgrade will not be

    able to take advantage of new types added to the typing module, such as

    typing.Protocol or typing.TypedDict.


    The typing_extensions module contains backports of these changes.

    Experimental types that will eventually be added to the ``typing``

    module are also included in typing_extensions.

    '
  dev_url: https://github.com/python/typing_extensions
  doc_url: https://github.com/python/typing_extensions/blob/main/README.md
  home: https://github.com/python/typing_extensions
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backported and Experimental Type Hints for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0feee086-308e-4d6c-9bd2-52e083881efe
  recipe-maintainers:
    - cbouss
  remote_url: git@github.com:AnacondaRecipes/typing_extensions-feedstock.git
  sha: 4ede6c5c83e4533a845b82aead578ce6cb441ddc
