# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: spdlog
  version: 1.11.0
source:
  patches:
    - async_test.patch
  sha256: ca5cae8d6cac15dae0ec63b21d6ad3530070650f68076f3a4a862ca293a858bb
  url: https://github.com/gabime/spdlog/archive/v1.11.0.tar.gz
build:
  number: 0
  run_exports:
    - spdlog >=1.11.0,<2.0a0
  string: h59b6b97_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_6
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.0 h966fe2a_2
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - fmt 9.1.0 h6d14046_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - fmt >=9.1.0,<10.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %PREFIX%\Library\include\spdlog\spdlog.h exit 1
about:
  description: 'spdlog is a header only library for Super fast C++ logging

    to be used with a C++11 compiler.

    '
  dev_url: https://github.com/gabime/spdlog
  doc_url: https://github.com/gabime/spdlog/wiki/1.-QuickStart
  home: https://github.com/gabime/spdlog
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Super fast C++ logging library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 801dac23-0369-4be0-9aff-cd0798758302
  recipe-maintainers:
    - bluescarni
    - druvus
    - rongou
  remote_url: git@github.com:AnacondaRecipes/spdlog-feedstock.git
  sha: ce0071cb793cfd6c85f53a912eadb9a51d786988
