# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# C:\b\abs_a0ullzukex\clone\recipe, last modified Tue Sep 24 17:58:42 2024
# ------------------------------------------------

package:
  name: anaconda_prompt
  version: 1.1.0
build:
  number: '0'
  string: haa95532_0
requirements:
  build: []
  run: []
  run_constrained:
    - anaconda-navigator >=1.9.8
    - menuinst >=2.1.1
test:
  commands:
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_prompt_menu.json EXIT 1
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_prompt.ico EXIT 1
app:
  entry: start cmd.exe /K "${CONDA_ROOT_PREFIX}\\Scripts\\activate.bat" "${CONDA_PREFIX}"
  icon: anaconda_prompt_win.png
  summary: Opens a terminal instance with conda activated (requires menuinst 2.1.1
    or greater).
  type: desk
about:
  description: 'Package to create shortcuts for terminals with an activated conda
    environment.

    '
  dev_url: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock
  doc_url: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock/blob/main/README.md
  home: https://github.com/AnacondaRecipes/anaconda_prompt-feedstock
  license: BSD-3-Clause AND CC-BY-NC-ND-4.0
  license_family: Other
  license_file:
    - LICENSE
    - LICENSE-BSD-3-Clause
    - LICENSE-CC-BY-NC-ND-4.0
  summary: Terminal shortcut creator for Anaconda
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a05c2f00-bf6b-4103-b95d-6161a12af52c
  recipe-maintainers:
    - marcoesters
  remote_url: git@github.com:AnacondaRecipes/anaconda_prompt-feedstock.git
  sha: 6bb215d7cebe17bfeb95f5639cde2ed952df3e22
