# This file created by conda-build 24.11.2
# ------------------------------------------------

package:
  name: libcurl
  version: 8.11.1
source:
  sha256: e9773ad1dfa21aedbfe8e1ef24c9478fa780b1b3d4f763c98dd04629b5e43485
  url: https://curl.se/download/curl-8.11.1.tar.bz2
build:
  ignore_run_exports:
    - krb5
  number: 0
  run_exports:
    - libcurl >=8.11.1,<9.0a0
  string: haff574d_0
requirements:
  build:
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2024.11.26 haa95532_0
    - krb5 1.20.1 h5b6d351_0
    - libssh2 1.11.1 h2addb87_0
    - openssl 3.0.15 h827c3e9_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - zlib 1.2.13 h8cc25b3_1
  run:
    - libssh2 >=1.10.0
    - libssh2 >=1.11.1,<2.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if exist %LIBRARY_BIN%\curl.exe exit 1
    - if exist %LIBRARY_LIB%\libcurl_a.lib exit 1
    - if not exist %LIBRARY_BIN%\libcurl.dll exit 1
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: aa45cf60-d387-4739-865c-0f1f6442e01c
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: 222172b88ec914c9001e3843b3f19058c422eb64
