# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_27dx58x550\clone\recipe, last modified Fri Dec 20 23:07:55 2024
# ------------------------------------------------

package:
  name: pydantic
  version: 2.10.3
source:
  sha256: cb5ac360ce894ceacd69c403187900a02c4b20b693a9dd1d643e1effab9eadf9
  url: https://pypi.io/packages/source/p/pydantic/pydantic-2.10.3.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_27dx58x550\\croot\\pydantic_1734736090499\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - hatch-fancy-pypi-readme 24.1.0 py312haa95532_0
    - hatchling 1.27.0 py312haa95532_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - packaging 24.2 py312haa95532_0
    - pathspec 0.10.3 py312haa95532_0
    - pip 24.2 py312haa95532_0
    - pluggy 1.5.0 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - trove-classifiers 2024.10.14 py312haa95532_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - annotated-types >=0.6.0
    - pydantic-core ==2.27.1
    - python >=3.12,<3.13.0a0
    - typing-extensions >=4.12.2
  run_constrained:
    - email-validator >=2.0.0
test:
  commands:
    - pip check
  imports:
    - pydantic
  requires:
    - pip
about:
  description: 'Data validation and settings management using python type hinting.

    See documentation doc_url for more details.

    '
  dev_url: https://github.com/pydantic/pydantic
  doc_url: https://docs.pydantic.dev/latest/
  home: https://github.com/pydantic/pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 27680f4b-7b65-4a63-91c2-3093f27ce5e0
  recipe-maintainers:
    - dgasmith
    - samuelcolvin
  remote_url: git@github.com:AnacondaRecipes/pydantic-feedstock.git
  sha: fff6a351cfd621c77cb96639c7ddb28d36b5fbff
