# This file created by conda-build 24.11.1
# meta.yaml template originally from:
# C:\b\abs_8b92fzmygg\clone\recipe, last modified Tue Nov 26 16:36:19 2024
# ------------------------------------------------

package:
  name: rich
  version: 13.9.4
source:
  sha256: 22bfd7f24f6107ed222f6ab0cee6f0016e22cb6f91144b90c65b112663c7477c
  url: https://github.com/Textualize/rich/archive/refs/tags/v13.9.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_8b92fzmygg\\croot\\rich_1732638991774\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - poetry-core 1.5.1 py312haa95532_0
    - python 3.12.7 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0,<3.0.0
    - python >=3.12,<3.13.0a0
  run_constrained:
    - ipywidgets >=7.5.1,<9
test:
  commands:
    - pip check
    - pytest -vv tests -k "not (test_markdown_render or test_syntax_highlight_ranges
      or test_option_no_wrap or test_python_render or test_card_render or test_brokenpipeerror
      or test_background_color_override_includes_padding)"
  imports:
    - rich
  requires:
    - attrs
    - pip
    - pytest
  source_files:
    - tests
about:
  description: "Rich is a Python library for rich text and beautiful formatting\n\
    in the terminal.The Rich API makes it easy to add color and style to\nterminal\
    \ output. Rich can also render pretty tables, progress bars,\nmarkdown, syntax\
    \ highlighted source code, tracebacks, and more \u2014 out\nof the box.\n"
  dev_url: https://github.com/Textualize/rich
  doc_url: https://rich.readthedocs.io/en/latest/
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the
    terminal.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8b8e27b9-e107-43c0-ac78-7da425babcf4
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
  remote_url: git@github.com:AnacondaRecipes/rich-feedstock.git
  sha: 0654e705fbbc3865fac02cb5c4b7df1cd72f37da
