# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_dfec_m79vo\clone\recipe, last modified Mon Dec  2 20:08:49 2024
# ------------------------------------------------

package:
  name: pluggy
  version: 1.5.0
source:
  fn: pluggy-1.5.0.tar.gz
  sha256: 2cffa88e94fdc978c4c574f15f9e59b7f4201d439195c3715ca9e2486f1d0cf1
  url: https://pypi.io/packages/source/p/pluggy/pluggy-1.5.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_dfec_m79vo\\croot\\pluggy_1733170145382\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - packaging 24.1 py312haa95532_0
    - pip 24.2 py312haa95532_0
    - python 3.12.7 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - setuptools-scm 8.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - pluggy
  requires:
    - pip
about:
  description: 'pluggy is the crystallized core of plugin management and hook calling
    for pytest.

    It enables 1400+ plugins to extend and customize pytest''s default behaviour.

    Even pytest itself is composed as a set of pluggy plugins which are invoked

    in sequence according to a well defined set of protocols.

    '
  dev_url: https://github.com/pytest-dev/pluggy/
  doc_url: https://pluggy.readthedocs.io
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: dfb83f9a-f78d-4829-ab44-5927e13302af
  recipe-maintainers:
    - JohnGreeley
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/pluggy-feedstock.git
  sha: b0f2ea667d8b73e7e013107fc3f4116807eb0339
