# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_55ez3326wm\clone\recipe, last modified Wed Dec 11 21:10:13 2024
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.7
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch
  sha256: 4cc540a3e9a1eebdefa1045d2e4184831100667e6d7d5b315bb1cbc951f8ddff
  url: https://github.com/libarchive/libarchive/releases/download/v3.7.7/libarchive-3.7.7.tar.gz
build:
  number: '0'
  run_exports:
    - libarchive >=3.7.7,<3.8.0a0
  string: h9243413_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - cmake 3.26.4 h693b641_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja-base 1.12.1 h4157e71_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - libiconv 1.16 h2bbff1b_3
    - libxml2 2.13.5 h24da03e_0
    - lz4-c 1.9.4 h2bbff1b_1
    - openssl 3.0.15 h827c3e9_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.2 h19a0ad4_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libiconv >=1.16,<2.0a0
    - libxml2 >=2.13.5,<2.14.0a0
    - lz4-c >=1.9.4,<1.10.0a0
    - openssl >=3.0.15,<4.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - pushd test-archives
    - bsdtar -vxf hello_world.xar 2>&1 | rg "x hello_world"
    - bsdtar -vxf archive.7z 2>&1 | rg "x 7zip-archive"
    - bsdtar -vxf hello_world.tar.zst 2>&1 | rg "greets"
    - popd
  files:
    - test-archives/archive.7z
    - test-archives/hello_world.tar.zst
    - test-archives/hello_world.xar
  requires:
    - ripgrep
about:
  description: 'Libarchive is an open-source BSD-licensed C programming library that
    provides streaming access

    to a variety of different archive formats, including tar, cpio, pax, Zip, and
    ISO9660 images.

    The distribution also includes bsdtar and bsdcpio, full-featured implementations
    of tar and cpio

    that use libarchive.

    When reading archives, libarchive uses a robust automatic format detector that
    can automatically handle archives

    that have been compressed with gzip, bzip2, xz, lzip, and several other popular
    compression algorithms.

    '
  dev_url: https://github.com/libarchive/libarchive
  doc_url: https://github.com/libarchive/libarchive/wiki
  home: https://libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5507bc81-6d9d-4dd6-a15a-8e4deda50d48
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libarchive-feedstock.git
  sha: c9e53b0c49fa581306bc6bb30f7ed84c251659da
