# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# C:\b\abs_e2lzchf4i6\clone\recipe, last modified Wed Nov 20 19:19:59 2024
# ------------------------------------------------

package:
  name: cryptography
  version: 43.0.3
source:
  sha256: 315b9001266a492a6ff443b61238f956b214dbec9910a081ba5b6646a055a805
  url: https://pypi.io/packages/source/c/cryptography/cryptography-43.0.3.tar.gz
build:
  number: '1'
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%
    - C:\\b\\abs_e2lzchf4i6\\croot\\cryptography_1732130411942\\_h_env\\python.exe
      -m pip install . -vv --no-deps --no-build-isolation
  string: py312hbd6ee87_1
requirements:
  build:
    - rust 1.82.0 h5da7b33_0
    - rust_win-64 1.82.0 h5da7b33_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.9.24 haa95532_0
    - cffi 1.17.1 py312h827c3e9_0
    - expat 2.6.3 h5da7b33_0
    - libffi 3.4.4 hd77b12b_1
    - maturin 1.3.1 py312h2bbff1b_0
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.12.7 h14ffc60_0
    - setuptools 72.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 h2eaa2aa_1
    - vs2015_runtime 14.40.33807 h98bb1dd_1
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - cffi >=1.12
    - openssl >=3.0.15,<4.0a0
    - python >=3.12,<3.13.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
  run_constrained:
    - bcrypt >=3.1.5
test:
  commands:
    - pip check
    - pytest tests
  requires:
    - certifi
    - cryptography-vectors 43.0.3.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e226978b-5b6e-4c4c-9676-81a1d459f703
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 7f71ebd7a05825a90011e57e561afc48ff4c61f7
