# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\Users\dev-admin\perseverance-python-buildout\aggregate\pygments-feedstock\recipe, last modified Wed Nov  8 19:28:06 2023
# ------------------------------------------------

package:
  name: pygments
  version: 2.15.1
source:
  sha256: 8ace4d3c1dd481894b2005f560ead0f9f19ee64fe983366be1a21e171d12775c
  url: https://pypi.io/packages/source/p/pygments/Pygments-2.15.1.tar.gz
build:
  entry_points:
    - pygmentize = pygments.cmdline:main
  number: '1'
  script: C:\\Users\\dev-admin\\perseverance-python-buildout\\croot\\pygments_1699474141968\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation
  string: py312haa95532_1
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - expat 2.5.0 hd77b12b_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3 py312haa95532_0
    - python 3.12.0 h1d929f7_0
    - setuptools 68.0.0 py312haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py312haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pygmentize -h
  imports:
    - pygments
    - pygments.filters
    - pygments.formatters
    - pygments.lexers
    - pygments.plugin
    - pygments.styles
  requires:
    - pip
about:
  description: 'This is the source of Pygments. It is

    a generic syntax highlighter written in Python

    that supports over 500 languages and text formats,

    for use in code hosting, forums, wikis or other applications

    that need to prettify source code.

    '
  dev_url: https://github.com/pygments/pygments
  doc_url: https://pygments.org/docs/
  home: https://pygments.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
    forums, wikis or other applications that need to prettify source code.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
    - scopatz
