# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_29_b57if3f\clone\recipe, last modified Mon Jan  6 17:22:12 2025
# ------------------------------------------------

package:
  name: cffi
  version: 1.17.1
source:
  patches:
    - 0001-Link-to-dl-library.patch
  sha256: 1c39c6016c32bc48dd54561950ebd6836e1670f2ae46128f67cf49e789c52824
  url: https://pypi.io/packages/source/c/cffi/cffi-1.17.1.tar.gz
build:
  missing_dso_whitelist: null
  number: '1'
  script: C:\\b\\abs_29_b57if3f\\croot\\cffi_1736184144340\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py312h827c3e9_1
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - pycparser
    - python >=3.12,<3.13.0a0
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - pip check
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen('ucrtbase'))"
  imports:
    - _cffi_backend
    - cffi
  requires:
    - pip
about:
  description: 'Cffi aims to allow users to call C code from Python without having
    to

    learn a 3rd language. It provides a convenient and reliable way to call

    compiled C code from Python using interface declarations written in C.

    '
  dev_url: https://github.com/python-cffi/cffi
  doc_url: https://cffi.readthedocs.io
  home: https://cffi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 299c2db6-c648-48e6-90ab-208d9f218ce9
  recipe-maintainers:
    - goanpeca
    - inducer
    - mingwandroid
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cffi-feedstock.git
  sha: 62c18dc6cf8a829936a4045dd046814ef57b98a2
