# This file created by conda-build 24.11.2
# ------------------------------------------------

package:
  name: simdjson
  version: 3.10.1
source:
  sha256: 1e8f881cb2c0f626c56cd3665832f1e97b9d4ffc648ad9e1067c134862bba060
  url: https://github.com/simdjson/simdjson/archive/v3.10.1.tar.gz
build:
  number: 0
  run_exports:
    - simdjson >=3.10.1,<3.11.0a0
  string: h214f63a_0
requirements:
  build:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.11.26 haa95532_0
    - cmake 3.26.4 h693b641_0
    - expat 2.6.4 h8ddb27b_0
    - libffi 3.4.4 hd77b12b_1
    - libmpdec 4.0.0 h827c3e9_0
    - libuv 1.48.0 h827c3e9_0
    - lz4-c 1.9.4 h2bbff1b_1
    - ninja 1.12.1 haa95532_0
    - ninja-base 1.12.1 h4157e71_0
    - openssl 3.0.15 h827c3e9_0
    - python 3.13.1 hadb2040_100_cp313
    - python_abi 3.13 0_cp313
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - vs2019_win-64 19.29.30154 h96f319f_5
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
    - zstd 1.5.6 h8880b57_0
  host:
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
  run:
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.29.30133,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\simdjson.h (exit 1)
    - if not exist %LIBRARY_BIN%\simdjson.dll (exit 1)
    - if not exist %LIBRARY_LIB%\simdjson.lib (exit 1)
    - if not exist %LIBRARY_LIB%\cmake\simdjson\simdjson-config.cmake (exit 1)
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson -DCMAKE_BUILD_TYPE=Release
      %CMAKE_ARGS%
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - cmake
    - ninja
    - vs2019_win-64
about:
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  dev_url: https://github.com/simdjson/simdjson/
  doc_url: https://simdjson.github.io/simdjson/
  home: https://simdjson.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ed4d1075-07df-456e-bd6f-b28c9f157ecb
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  remote_url: git@github.com:AnacondaRecipes/simdjson-feedstock.git
  sha: 751e747ff65ed7f4c599e297a43a84ae810be04c
