# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# C:\b\abs_494cm143zh\clone\recipe, last modified Fri Jan 10 23:02:04 2025
# ------------------------------------------------

package:
  name: truststore
  version: 0.10.0
source:
  fn: truststore-0.10.0.tar.gz
  sha256: 12e89641dba78a9427f782ad2d824bed93583a9465002fe59b63c3fd12cbe8f5
  url: https://github.com/sethmlarson/truststore/archive/refs/tags/v0.10.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_494cm143zh\\croot\\truststore_1736550137835\\_h_env\\python.exe
    -m pip install . -vv --no-deps --no-build-isolation
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2024.12.31 haa95532_0
    - expat 2.6.4 h8ddb27b_0
    - flit-core 3.9.0 py312he100be2_1
    - libffi 3.4.4 hd77b12b_1
    - openssl 3.0.15 h827c3e9_0
    - pip 24.2 py312haa95532_0
    - python 3.12.8 h14ffc60_0
    - setuptools 75.1.0 py312haa95532_0
    - sqlite 3.45.3 h2bbff1b_0
    - tk 8.6.14 h0416ee5_0
    - tzdata 2024b h04d1e81_0
    - vc 14.40 haa95532_2
    - vs2015_runtime 14.42.34433 h9531ae6_2
    - wheel 0.44.0 py312haa95532_0
    - xz 5.4.6 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v -s -rs --no-flaky-report --max-runs=3 tests/
  imports:
    - truststore
  requires:
    - aiohttp
    - flaky
    - httpx
    - pip
    - pyopenssl
    - pytest
    - pytest-asyncio
    - pytest-httpserver
    - requests
    - trustme
    - urllib3
  source_files:
    - tests
about:
  description: "A library which exposes native system certificate stores (ie \u201C\
    trust stores\u201D)\nthrough an ssl.SSLContext-like API. This means that Python\
    \ applications no\nlonger need to rely on certifi as a root certificate store.\n"
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/
  home: https://github.com/sethmlarson/truststore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Verify certificates using native system trust stores
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 49e05b68-98aa-4292-97e8-7bcf1b7e8773
  recipe-maintainers:
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/truststore-feedstock.git
  sha: 54e19d1b31e86cb72438537bf2fd45b4c0d3ef6b
